### ISSUE TITLE
No component found for view with name "RNSVGGroup"

### ISSUE THREAD

**Issue by wvicioso** [capitalone/react-native-pathjs-charts#102]
I keep getting this error `No component found for view with name "RNSVGGroup"` while trying to run it on ios.

I used installed with `npm install react-native-pathjs-charts --save`
I ran `react-native link react-native-svg`
I put this atop my file `import { Bar } from 'react-native-pathjs-charts'`

In xcode > Libraries > RNSGV.xcodeproj > Build Phases > Link Binary With Libraries,
I found that it is empty. When I go to add a library, `libRNSVG.a` is not found.

I have rebooted the emulator. I have deleted the node-modules file and reinstalled. When I try to unlink the svg with `react-native unlink react-native-svg` I get this error:
```
rnpm-install ERR! It seems something went wrong while unlinking. Error: Cannot read property 'config' of undefined

Cannot read property 'config' of undefined 
```

This was working for me last week. I do not know what's going on now. If anyone could offer some help it would be appreciated!

**Comment by marzolfb** [comment]
What is the output of this statement for you:

```
npm list react-react-native react-native-svg
```

**Comment by wvicioso** [comment]
```
├─┬ react-native-pathjs-charts@0.0.26
│ └── react-native-svg@4.5.0
└── react-native-svg@5.1.5
```

I get this @marzolfb

**Comment by marzolfb** [comment]
You edited this and it looks like you had react-native-svg 5.1.5 in your root. Is that still the case? If so it conflicts with the version in react-native-pathjs-charts and I'll give the same advice that I did in #101 which is to downgrade to react-native-svg 4.5.0.

**Comment by wvicioso** [comment]
I noticed that and continued to downgrade to 4.5.0. I do not get a build error any more but I still get get this when I try to render a bar graph `No component found for view with name "RNSVGGroup"`

**Comment by marzolfb** [comment]
Hmm. Android or iOS? Close all console windows and emulators and start everything back up again - same result? Also, try removing all npm packages with `rm -rf node_modules` and starting from scratch with a fresh set of dependencies via `npm install`? Still, same result?

**Comment by wvicioso** [comment]
Just reloaded everything and still getting the same error for IOS

**Comment by marzolfb** [comment]
One more time on the version info on critical dependencies - what do you get with this:

```
npm list react react-native react-native-svg paths-js
```

?

**Comment by wvicioso** [comment]
├── react@15.4.2
├── react-native@0.41.0
└─┬ react-native-pathjs-charts@0.0.26
  ├── paths-js@0.4.5
  └── react-native-svg@4.5.0

**Comment by marzolfb** [comment]
And you did this after you refreshed everything this last time:

```
react-native link react-native-svg
```

?

**Comment by wvicioso** [comment]
I guess I did not. Right now I linked then rebuilt and theres the graph. Everything is working perfect. Thank you. I think my issue was not rebuilding after I linked.

**Comment by daiict218** [comment]
there is still this issue. It asks us to downgrade react-native-svg to 4.5.0 but installs versions ~5.1.8 itself, So even if we downgrade the react-native-svg, it gives the same error. Can someone help?

**Comment by fawwaz** [comment]
I experience the same issue as @daiict218 , I've linked the react-native-svg in both ways (using `react-native link` and in manual way - e.g : adding `SvgPackage` to `MainApplication.java`)

**Comment by daiict218** [comment]
@fawwaz actually It doesn't ask to downgrade react-native-svg, it just wants us to install same version in both the repos. So, I installed react-native-svg ~5.1.8 in my code and it worked fine for me.

**Comment by aurelienroux** [comment]
Hi, I'm having the same problem here with. I tried to install previous version react-native-svg@4.5.0 directly but the @5.1.8 is still present and I'm not sure how to change this. Can someone help ? Thanks

├── UNMET PEER DEPENDENCY react@16.0.0-alpha.3
└─┬ react-native-pathjs-charts@0.0.28
  ├── UNMET PEER DEPENDENCY react@16.0.0-alpha.6
  └── react-native-svg@5.1.8

**Comment by wvicioso** [comment]
@aurelienroux Hi, try these steps
1) `npm uninstall react-native-svg`
2) `npm install react-native-svg@4.5.0`
3) check in your package.json file where react-native-svg is listed that the version number doesn't have a `^` symbol preceding it. If it does, just remove that symbol leaving only the version number
4) delete node-modules folder then run `npm install && react-native link && react-native link react-native-svg`

**Comment by aurelienroux** [comment]
@wvicioso thanks for the help
I still have the same issue. it seems the react-native-svg dependency in react-native-pathjs-charts is overriding the other version I install manually

├── UNMET PEER DEPENDENCY react@16.0.0-alpha.3
├─┬ react-native-pathjs-charts@0.0.28
│ ├── UNMET PEER DEPENDENCY react@16.0.0-alpha.6
│ ├── UNMET PEER DEPENDENCY react-native@>=0.44.0
│ └── react-native-svg@5.1.8
└── react-native-svg@4.5.0

I can see the 4.5.0 installed but I think the 5.1.8 is coming directly from the pathjs package and is taking priority. Is there a way to change a dependency version in a package ?

thanks again

**Comment by wvicioso** [comment]
@aurelienroux try installing  `react-native-pathjs-charts@0.0.26` instead of 0.28. I'm not sure how to change only the dependency under pathjs-chart.

**Comment by wvicioso** [comment]
You could also try sticking with the version you have and try running `react-native unlink react-native-svg && react-native link react-native-svg@4.5.0`

**Comment by aurelienroux** [comment]
@wvicioso neither solutions are working. And I'm sure it's coming from this particular project but I don't know what is causing the bug. I have installed the examples folder somewhere else and it's working without any problems.

anyway, thanks for helping, I'll try to look at other solutions

**Comment by marzolfb** [comment]
@aurelienroux What versions of everything (this lib, react, react-native, rn-svg, pathjs) are you trying to use? Are you just trying to use the latest version of everything that will work together or are you trying to target specific versions of one of this things mentioned above? There is a delicate and unfortunate connectedness with all of these libraries and some versions just aren't compatible with others. 

@fawwaz are you also still having similar issues? I'm trying to determine if this is still an issue multiple people have or if problems are unique in each case  (if so I will reopen this and we can continue discussing here - if not, @aurelienroux and I can continue troubleshooting on her new issue opened up (#162)

**Comment by aurelienroux** [comment]
@marzolfb Hi
the project was started with [Ignite react boilerplate](https://github.com/infinitered/ignite).
I'm not trying to target specific versions but I thought my problem was coming from react-native-svg version and tried to downgrade it, without any success as I still have the error message "No component found for view with name "RNSVGGroup.

here are the actuals version
    "react": "16.0.0-alpha.3",
    "react-native": "0.43.1",
    "react-native-config": "^0.2.1",
    "react-native-pathjs-charts": "0.0.28",

thanks

**Comment by marzolfb** [comment]
So, the latest version of react-native-pathjs-charts (0.0.28) depends on react-native-svg 5.1.8 and the react-native-svg says this:

```react-native-svg >= 5.1.8 only supports react-native >= 0.44.0 and react == 16.0.0-alpha.6```

I would start from scratch and remove everything:
```rm -rf node_modules```

Then, change your package.json to point to the versions of react && react-native I mention above and finally reinstall with npm/yarn.

The example app in this library uses those versions mention above, which is why your earlier comment about the example app working correctly makes sense.

**Comment by aurelienroux** [comment]
Problem is still here, event with new package versions. I'm still receiving No component found for view with name "RNSVPGroup". 
I removed all node modules and reinstalled, created the link, restarted the simulator but it's still not working

├── UNMET PEER DEPENDENCY react@16.0.0-alpha.6
├── react-native@0.44.0
└─┬ react-native-pathjs-charts@0.0.28
  ├── paths-js@0.4.5
  └── react-native-svg@5.1.8

**Comment by marzolfb** [comment]
This line specifically:

```UNMET PEER DEPENDENCY react@16.0.0-alpha.6```

is telling you that you don't have react v16.0.0-alpha.6 installed which react-native-svg 5.1.8 depends on. What does your package.json file look like in all of the dependencies sections?

**Comment by aszheng** [comment]
I am also having a similar issue. I tried the examples above and even downgraded to `react-native-pathjs-charts@0.0.26`

Here is what I get after `npm list react react-native react-native-svg paths-js`
`├── paths-js@0.4.5 
├── react-native@0.44.2 
├─┬ react-native-pathjs-charts@0.0.26
│ ├── paths-js@0.4.5  deduped
│ └── react-native-svg@4.5.0  deduped
└── react-native-svg@4.5.0 `

**Comment by aurelienroux** [comment]
sorry for the delay. my package.json looks like this
    "react": "16.0.0-alpha.3",
    "react-native": "0.43.1",

**Comment by glawson** [comment]
I believe this to be an install/link issue with the react-native-svg package.  What I did to solve this:
1.  Add the RNSVG.xcodeproj to my app's Libraries.
2. Add the libRNSVG.a lib to the Link Binary With Libraries section under my app project's Build Phases. 
Basically, follow the instructions to manually link the library at https://facebook.github.io/react-native/docs/linking-libraries-ios.html
