### ISSUE TITLE
Using dates on X axes

### ISSUE THREAD

**Issue by obukhow** [capitalone/react-native-pathjs-charts#107]
I cannot directly set date to x property of a coordinate. May be there is a way to add a label for each point?

**Comment by huttj** [comment]
Is this what you're looking for?

https://github.com/capitalone/react-native-pathjs-charts/blob/master/example/src/stockline/StockLineChartDynamicTickLabels.js#L65

**Comment by obukhow** [comment]
@huttj thank you very much!
