### ISSUE TITLE
Resize Pie Chart

### ISSUE THREAD

**Issue by mochamadArif** [capitalone/react-native-pathjs-charts#114]
How to resize pie chart? (Radius of center and size all chart)

**Comment by RealAmissio** [comment]
have you solved the problem? can you tell me how to resize pie chart? (Radius of center and size all chart),thank you

**Comment by RealAmissio** [comment]
i have solved,thanks

**Comment by mochamadArif** [comment]
@RealAmissio 
lol forgot to post the answer.
Set `r` and `R` for radius and then `width` and `height` to resize container of the chart
