### ISSUE TITLE
JSON value '<null>' of type NSNull cannot be converted to NSNumber

### ISSUE THREAD

**Issue by 360disrupt** [capitalone/react-native-pathjs-charts#115]
In the example below I give always back `10` in the labelFunction no matter what the input of `x` is. So there should be no difference what I initially pass for `x`.
If I change the passed prop from:
`history = [{x:0, y:10},{x:1, y:20}]`  to `history = [{x:"2017-03-16T14:44:24.815Z", y:10},{x:"2017-03-17T14:44:24.815Z", y:20}]` it throws an exception:

![bildschirmfoto 2017-03-16 um 15 56 12](https://cloud.githubusercontent.com/assets/7427903/24002497/3412aa7e-0a61-11e7-8183-02ad7bad0ab6.png)

# Chart
```
import React, { Component, PropTypes } from 'react';
import { View, Text, Navigator } from 'react-native';
import moment from 'moment/src/moment';

import { SmoothLine } from 'react-native-pathjs-charts'

class Chart extends Component {
  static propTypes = {
    history: PropTypes.array.isRequired
  }

  render() {
    let options = {
      width: 280,
      height: 280,
      color: '#2980B9',
      margin: {
        top: 20,
        left: 45,
        bottom: 25,
        right: 20
      },
      animate: {
        type: 'delayed',
        duration: 200
      },
      axisX: {
        showAxis: true,
        showLines: true,
        showLabels: true,
        showTicks: true,
        zeroAxis: false,
        orient: 'bottom',
        labelFunction: ((value) => {
          // let xLabel = moment(value).format('HH:mm:ss');
          // console.log(value, " " ,xLabel);
          let xLabel = 10;
          return xLabel
        }),
        label: {
          fontFamily: 'Arial',
          fontSize: 14,
          fontWeight: true,
          fill: '#34495E'
        }
      },
      axisY: {
        showAxis: true,
        showLines: true,
        showLabels: true,
        showTicks: true,
        zeroAxis: false,
        orient: 'left',
        label: {
          fontFamily: 'Arial',
          fontSize: 14,
          fontWeight: true,
          fill: '#34495E'
        }
      }
    }
    console.log("rendering", this.props.history);
    return (
      <View>
        <SmoothLine data={[this.props.history]} options={options} xKey='x' yKey='y' />
      </View>
    )
  }
}
module.exports = Chart;
```

**Comment by marzolfb** [comment]
Yes, Smoothline is making an assumption you are providing numbers in your dataset. I haven't thought too much about how you can work around this based on your question but it seems like you are wanting to do something similar to the StockLineChartDynamicTickLabels example in the example app:

https://github.com/capitalone/react-native-pathjs-charts/blob/master/example/src/stockline/StockLineChartDynamicTickLabels.js#L65

Does that help at all?

**Comment by marzolfb** [comment]
@360disrupt Did the feedback above help address your issue?

**Comment by AtifJaved1** [comment]
Hi, I have used Pie-Char basic example in the Repo. But My Application now starts crashing upon startup. And sometimes it shows error same as the above attached by @360disrupt but instead of null its 3. Please let me know about this issue.

**Comment by marzolfb** [comment]
What does your chart options and data look like? What does `npm list react react-native react-native-svg` show?

**Comment by AtifJaved1** [comment]
This is what I am using, same code https://github.com/capitalone/react-native-pathjs-charts/blob/master/src/Pie.js
npm list react react-native react-native-svg: this command shows:

react-native-pathjs-charts@0.0.31
│ └── react-native-svg@5.4.2 
└── react-native-svg@6.0.0

**Comment by marzolfb** [comment]
You will want to remove that 6.0.0 version of react-native-svg. Also, repeating a comment I made on #209: 

I just published a new version of this library with the most updated/working dependencies. So, if you do a 

```
rm -rf node_modules && npm cache clean && npm install
```

(or equivalent), and you do this: 

```
npm list react-native-pathjs-charts react-native react react-native-svg
```

, you should now see something like: 

```
├── react@16.0.0 
├── react-native@0.50.3 
└─┬ react-native-pathjs-charts@0.0.32 
  └── react-native-svg@5.5.1 
```

Does that help?

**Comment by AtifJaved1** [comment]
@marzolfb Thanks for the update, I will follow your comment and will let you know if that helps.
Thanks again
