### ISSUE TITLE
Pie chart with 1 item in the midle not Transparent

### ISSUE THREAD

**Issue by NeETsu** [capitalone/react-native-pathjs-charts#124]
Hello
as first great chart tool :)

i am using the tool to display pie chart dynamically (building the chart when the user selects the data to display). I am also showing with a Text in the middle of the Chart. I found that if i have only one item selected (drawing the chart with only 1 Item) then the middle of the Chart is not Transparent but white.

Is these a known Issue?

**Comment by marzolfb** [comment]
I was unable to reproduce this behavior when I edited the PieChartBasic and removed all but one data point. I wonder if you are using different versions of dependencies. What happens when you issue this command in your app:

```
npm list react-react-native react-native-svg paths-js
```

?

When I do this with the example app, I see this:
```
react-native-pathjs-charts@0.0.26
  ├── paths-js@0.4.5 
  └── react-native-svg@4.5.0
```

**Comment by NeETsu** [comment]
hello
when i run the command i see:

```
└─┬ react-native-pathjs-charts@0.0.26
  ├── paths-js@0.4.5
  └── react-native-svg@4.5.0
```
the result is seen below.

<img width="244" alt="screen shot 2017-03-27 at 07 07 12" src="https://cloud.githubusercontent.com/assets/23639361/24341751/35113d88-12bc-11e7-9892-b18ebc8d0180.png">
<img width="234" alt="screen shot 2017-03-27 at 07 07 03" src="https://cloud.githubusercontent.com/assets/23639361/24341754/39199c0e-12bc-11e7-8884-23886a6fccf8.png">

the result is seen beacuse i have a grey background. Before i also had text behind the chart and was not shown if i only selected one item.

**Comment by NeETsu** [comment]
Hello
just found the Issue and a workaround.
in case of one item it are not the arches drawn but a full circle in a full circle. 

There is a parameter called `monoItemInnerFillColor` where you can set the color of the inner circle
