### ISSUE TITLE
Bar Chart Color Pattern

### ISSUE THREAD

**Issue by riftshock** [capitalone/react-native-pathjs-charts#134]
Hey Nice Package Btw man! There's not a lot of good packages out there in react-native in supporting charts for now. So this was kind of very helpful for me.

So The way I Understand it Bar Charts Supports 3 Colors (1 color that is just being darkened for a pattern of 3) so if I have a data of : 
      [{ 
          "value": 100,
          "name": "apple",
        }, {
          "value": 100,
          "name": "apple",
        }, ],
      [{
          "value": 100,
          "name": "banana",
        }, {
          "value": 100,
          "name": "banana",
        },],
      [{
          "value": 100,
          "name": "grape",
      }, {
          "value": 100,
          "name": "grape",
      }, ]

So I will have a graph that looks like this:
**Image1:**
![Imgur](http://i.imgur.com/TroypQe.jpg)

My Problem is that when I have a data which has a group of 2 or more than 3 (shown in image 2&3) The Pattern of 3 colors still remains.

**Image2**
![Imgur](http://i.imgur.com/mGYwN81.jpg)

**Image3**
![Imgur](http://i.imgur.com/jyxkpMk.jpg)

Is There a way that I could color the bars by group. Like 2 colors per group of 2 bars and 4 colors per group of 4 bars?? Anyway man Really loved your work. I'm so grateful for this one. Hope to hear from you soon. Thank You =)

**Comment by marzolfb** [comment]
Yes - certainly a bug. Thanks for the compliments and sorry for the delay in responding. Interesting that no one has caught this before. So, thanks for submitting it. I just addressed this in a new pull request and we will get that merged in soon.

**Comment by riftshock** [comment]
@marzolfb  Thank You for the fix. Really appreciate it, was wondering if you could publish the changes to the npm. Anyways thanks man =) so happy for this.

**Comment by marzolfb** [comment]
Done. Thanks for the nudge.
