### ISSUE TITLE
xcode'error unknow class method in the running App

### ISSUE THREAD

**Issue by cuiyueshuai** [capitalone/react-native-pathjs-charts#15]
Hi, I add react-native-pathjs-charts and link this in the my project.
when running, Xcode'error: "unknow class method for selector UIFont:nil withFamily:fontDict[@"fontFamily"] size:fontDict[@"fontSize"] weight:fontDict[@"fontWeight"] style:fontDict[@"fontStyle"] scaleMultiplier:1.0]; " in the "RNSVG/Utils/RCTConvert+RNSVG.m".
I think the react-native-svn'version is too old, so I npm install react-native-svn@latest and again link, I find the code is different about upper description, and I success run app, but I don't see chats, I still failed.
I don't know the reason, who can tell me why is it that?

**Comment by marzolfb** [comment]
When you say  react-native-svn'version is too old, I'm guessing you mean react-native-svg. #16 indicated the same issue and I just pushed an updated release to the public npm registry. Try again with a clean `npm install` which should pull more recent versions of the dependencies and will likely fix your issue. We can reopen if a problem still exists after updating.
