### ISSUE TITLE
How can I format the values in axis.

### ISSUE THREAD

**Issue by themathiou** [capitalone/react-native-pathjs-charts#151]
I need to format the values in x and y axis but I cannot find any example describing that in the documentation.
Is there any example somewhere?

**Comment by marzolfb** [comment]
Take a look at the static and dynamic label variations of the StockLine chart in [the example app](https://github.com/capitalone/react-native-pathjs-charts/tree/master/example) - those techniques should apply to other chart types as well.

**Comment by themathiou** [comment]
Great! Thanks!
It's very useful feature. I suggest you to move it in the basic examples.
