### ISSUE TITLE
Got No view Manager defined for class RNSVGGroup

### ISSUE THREAD

**Issue by fawwaz** [capitalone/react-native-pathjs-charts#154]
This is my package.json :
```json
{
  "dependencies": {
    "lodash": "^4.17.4",
    "react": "^15.4.2",
    "react-native": "^0.42.0",
    "react-native-pathjs-charts": "0.0.28",
    "react-native-side-menu": "^0.20.1",
    "react-native-simple-table": "0.0.2",
    "react-native-sqlite-storage": "^3.3.1",
    "react-native-svg": "^5.1.7",
    "react-native-tab-view": "0.0.63",
    "react-native-vector-icons": "^4.1.1",
    "react-navigation": "^1.0.0-beta.9",
    "react-redux": "^5.0.4",
    "redux": "^3.6.0",
    "redux-logger": "^3.0.1",
    "redux-thunk": "^2.2.0"
  },
  "jest": {
    "preset": "react-native"
  },
  "devDependencies": {
    "babel-jest": "^20.0.0",
    "babel-preset-react-native": "^1.9.1",
    "jest": "^20.0.0",
    "react-test-renderer": "^15.5.4",
    "remote-redux-devtools": "^0.5.7"
  }
}
```
I've run `rnpm link react-native-svg`, I also triple check that the library manually (Adding `import com.horcrux.svg.SvgPackage;` to `MainApplication.java` and adding `new SvgPackage()` in `getPackage()`.

**Comment by ljy0605** [comment]
me too。

**Comment by ljy0605** [comment]
you should install svg,i solve it。

**Comment by fdiep** [comment]
Hey @ljy0605 How did you solve the issue? I get the issue with RNSVGGroup as well.

Thanks!

**Comment by fdiep** [comment]
Got it to work. Had to manually link the library for `react-native-svg`

**Comment by bravokeyl** [comment]
@fawwaz , Try uninstalling the app on device/simulator and then re-install it.

**Comment by marzolfb** [comment]
@fawwaz and others, The current version of this library depends on react-native-svg 5.1.8 and that only supports react-native >= 0.44.0 and react == 16.0.0-alpha.6. Updating your dependencies to newer versions should help
