### ISSUE TITLE
Add press event to labels of radar chart

### ISSUE THREAD

**Issue by Shagamii** [capitalone/react-native-pathjs-charts#161]
Is there a function to trigger an event when pressing an label on a radar chart?

Before filing an issue please ensure the following boxes are checked, if applicable:

- [x] I have searched for existing issues
- [x] I have provided detailed instructions that can reproduce the issue (including code and data necessary)

**Comment by marzolfb** [comment]
Merged pull request #164 addresses this one - so closing it out.
