### ISSUE TITLE
No component found for view with name "RNSVGGroup"

### ISSUE THREAD

**Issue by aurelienroux** [capitalone/react-native-pathjs-charts#162]
Hi, I think I'm having the same problem as #102, but I don't understand how to change react-native-svg version. here is my list 

├── UNMET PEER DEPENDENCY react@16.0.0-alpha.3
└─┬ react-native-pathjs-charts@0.0.28
  ├── UNMET PEER DEPENDENCY react@16.0.0-alpha.6
  └── react-native-svg@5.1.8

can somebody help, please ?

**Comment by Minishlink** [comment]
`react-native-pathjs-charts` should upgrade its `react-native-svg` dependency to 5.2.0 (fixed in https://github.com/react-native-community/react-native-svg/issues/340 )
