### ISSUE TITLE
Build failed in RN 0.45.1 (iOS)

### ISSUE THREAD

**Issue by sajjadrad** [capitalone/react-native-pathjs-charts#169]
Hi, 
I have some problems in building in xcode. First there was some errors about importing React in RNSVG. after solving that now this error occurs:
`clang: error: linker command failed with exit code 1 (use -v to see invocation)
`
This happened after linking react-native-svg.

xcodebuild command:
`The following build commands failed:
	CompileC build/Foo.build/Release-iphonesimulator/foo.build/Objects-normal/x86_64/AppDelegate.o foo/AppDelegate.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler`

react-native run-ios command:
`The following build commands failed:
Ld build/Build/Products/Debug-iphonesimulator/Foo.app/Foo normal x86_64`

RN : 0.45.1
iOS

**Comment by sajjadrad** [comment]
After unlinking react-native-svg, app starts normally but with RNSVG not found error.

**Comment by csdwd** [comment]
I also encountered the same problem.
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`
```
 "react": "16.0.0-alpha.12",
    "react-native": "0.46.1",
    "react-native-pathjs-charts": "0.0.29",
    "react-navigation": "^1.0.0-beta.11"
```

**Comment by marzolfb** [comment]
There's an incompatibility problem between the version of react-native-svg this lib uses (~5.2.0) and the react-native-svg version (~5.3.0) that is compatible with the latest stable react-native version (0.46.1). Once #170 gets completed, merged in, and a new version of this lib gets pushed to npm, hopefully the errors seen on this issue will disappear.

**Comment by sajjadrad** [comment]
@marzolfb Thanks for answer, how much time do you estimate for these actions?

**Comment by marzolfb** [comment]
@sajjadrad Just pushed a new version to npm a little bit ago. Give it a try and let me know how it goes.

**Comment by sajjadrad** [comment]
@marzolfb I upgraded your package to 0.0.30 and rn-svg to 5.3 but I have same error after linking while building.

**Comment by marzolfb** [comment]
I will likely need some more details to help. What are your installed versions of dependencies - what is the out of this 

```npm list react react-native react-native-svg paths-js```

?  

Also, what is your Xcode version?

Also, I assume you experience this with your own app and trying to use this library but have you tried building/running the example app? Do you experience the same issue?

**Comment by sajjadrad** [comment]
`├── react@16.0.0-alpha.12 
├── react-native@0.46.1 
├─┬ react-native-pathjs-charts@0.0.30
│ ├── paths-js@0.4.5 
│ └── react-native-svg@5.3.0 
└── react-native-svg@5.3.0`

Xcode 8.3.1

Example app works properly. I think I have problems with react-native-svg package. It installed twice 🤔

**Comment by sajjadrad** [comment]
I uninstalled react-native-pathjs-charts and react-native-svg and install react-native-pathjs-charts again. this is my list output now:

`├── react@16.0.0-alpha.12 
├── react-native@0.46.1 
└─┬ react-native-pathjs-charts@0.0.30
  ├── paths-js@0.4.5 
  └── react-native-svg@5.3.0`

After linking react-native-svg with `react-native link react-native-svg` command, I have `clang: error: linker command failed with exit code 1 (use -v to see invocation)` error :(

**Comment by marzolfb** [comment]
What happens if you start from scratch: 
```
rm -rm node_modules
npm install
react-native link react-native-svg
react-native run-ios
```

Same error?

What other troubleshooting steps have you tried?

Is there any more to the error chain that could be helpful?

**Comment by sajjadrad** [comment]
Same error after linking, and run ok after unlink react-native-svg

**Comment by marzolfb** [comment]
What are the differences between the example app and your app? Is the source/package.json for your app available somewhere publicly that I (and/or others) could try to reproduce the problem you are experiencing?

**Comment by sajjadrad** [comment]
@marzolfb I checked react-native-svg issues and found [this](https://github.com/react-native-community/react-native-svg/issues/366).

After removing RNSVG-TV schema, it works.

Thanks
