### ISSUE TITLE
There are no numbers for axis on android

### ISSUE THREAD

**Issue by SimchaShats** [capitalone/react-native-pathjs-charts#17]
![screen shot 2016-11-08 at 12 26 45 pm](https://cloud.githubusercontent.com/assets/19427778/20095567/a8a15998-a5ae-11e6-8d06-5ada650c5214.png)

Before filing an issue please ensure the following boxes are checked, if applicable:

Hi I'm using react-native 0.32, and there are no numbers for axis on android, only one in top left corner. 

I checked for bar graph... there are also no labels on axis...

**Comment by marzolfb** [comment]
[We just updated the version of react-native-pathjs-charts](https://github.com/capitalone/react-native-pathjs-charts/releases/tag/0.0.21) and it now has updated versions of react-native and react-native-svg. These updates may address your issues. Try updating to this newer release and see if that helps. If it doesn't, could you include your sample code and data that produced the screenshot above?

**Comment by SimchaShats** [comment]
I update to 0.37, the same thing... Here is my data:
`stockLine: [[{"x":6,"y":58},{"x":7,"y":58},{"x":8,"y":83}]];
bar: [[{"name":"6","v":3},{"name":"7","v":3},{"name":"8","v":3}]]`
Here is my Code: 
````
export default class extends Component {
  constructor(props) {
    super(props);
    this.state = {
      stockLine: [[{
        "x": 0,
        "y": 0
      }, {
        "x": 1,
        "y": 1
      }, {
        "x": 2,
        "y": 2
      }]],
      bar: [[{
        "v": 0,
        "name": "0"
      }, {
        "v": 1,
        "name": "1"
      }, {
        "v": 2,
        "name": "2"
      }]]
    }
  }

  componentWillReceiveProps(nextProps) {
    /*... here some calculations*/
  }

  shouldComponentUpdate(nextProps, nextState) {
    /*... here some calculations*/
  }

  render() {
    return (
      <View style={styles.container}>
        <ScrollView style={{flex: 1}} contentContainerStyle={{justifyContent: 'center', alignItems: 'center'}}>
          <Text style={styles.graphTitle}>{I18n.t("graphTitleProgress")}</Text>
          {this.props.statisticalData.size < 3 ? <Text>{I18n.t("graphMinimum3Days")}</Text> :
            <StockLine data={this.state.stockLine} options={config.stockLine.options} xKey='x' yKey='y'/>}
          <Text style={styles.graphTitle}>{I18n.t("graphTitleActivity")}</Text>
          {this.props.statisticalData.size < 3 ? <Text>{I18n.t("graphMinimum3Days")}</Text> :
            <Bar data={this.state.bar} options={config.bar.options} accessorKey='v'/>}
          <Pie
            data={config.pie.data}
            options={config.pie.options}
            accessorKey="population" />
        </ScrollView>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: "row"
  },
  graphTitle: {
    fontSize: 14,
    padding: 10,
    fontWeight: "bold",
    color: "gray",
    textAlign: "center"
  },
  content: {
    flex: 1,
  }
});
```
`

**Comment by marzolfb** [comment]
Thanks for the example code and data. I am not seeing the same thing:

![image](https://cloud.githubusercontent.com/assets/1242149/20149485/5deb0c4c-a666-11e6-9742-f35552ac0f4b.png)

I got this screenshot by plugging in your [MyNotesStatisticalPeriod.txt](https://github.com/capitalone/react-native-pathjs-charts/files/580230/MyNotesStatisticalPeriod.txt) attachment into the example app for the project. I had to tweak your example slightly and hard code your example data above to make it work. My resulting tweaked file is here - [index.android.js.txt](https://github.com/capitalone/react-native-pathjs-charts/files/581540/index.android.js.txt)

One obvious difference between my screenshot and yours is that you are using Genymotion and I'm not. Do you see other differences that may provide a clue to understanding the rendering difference?

Could you try using my tweaked file on your Genymotion-based setup and see if you see the same thing?  Do you have another example that may illustrate/reproduce the issue better?

**Comment by SimchaShats** [comment]
I tried the real device android
![screenshot_2016-11-10-10-56-45](https://cloud.githubusercontent.com/assets/19427778/20170547/78a11d9a-a735-11e6-9a78-94aafb54f368.png)
... the same thing all numbers on the left top corner...

**Comment by marzolfb** [comment]
Would you be willing to embed/attach the Axis.js source you have? I'm not sure I understand what your "if in file Axis.js wrap tag with it" comment means.

**Comment by Jarda8** [comment]
I have a similar issue as SimchaShats again. The labels on the bar chart are not displaying at all. I have the latest version - 0.0.21 (downloaded today).
code:
```
export class ExpensesBarchart extends Component {
  render() {
    var data = [
        [{
          "amount": 700,
          "name": "1. week"
        }, {
          "amount": 1500,
          "name": "2. week"
        }, {
          "amount": 900,
          "name": "3. week"
        }, {
          "amount": 3000,
          "name": "4. week"
        }]
      ];

    var options = {
      width: 250,
      height: 250,
      color: '#2980B9',
      gutter: 20,
      animate: {
        type: 'oneByOne',
        duration: 200,
        fillTransition: 3
      },
      axisX: {
        showAxis: true,
        showLines: true,
        showLabels: true,
        showTicks: true,
        zeroAxis: false,
        orient: 'bottom',
        label: {
          fontFamily: 'Arial',
          fontSize: 8,
          fontWeight: true,
          fill: '#34495E'
        }
      },
      axisY: {
        showAxis: true,
        showLines: true,
        showLabels: true,
        showTicks: true,
        zeroAxis: false,
        orient: 'left',
        label: {
          fontFamily: 'Arial',
          fontSize: 8,
          fontWeight: true,
          fill: '#34495E'
        }
      }
    };

    return (
      <View style={ flex: 1, alignItems: "center", justifyContent: "center" }>
        <Bar
          data={data}
          options={options}
          accessorKey="amount" />
      </View>
    );
  }
}
```
result:
![image](https://cloud.githubusercontent.com/assets/15692609/20239748/f197cb76-a907-11e6-9785-b589bd57faba.png)

I am running it with Exponent (11.0.0) on Genymotion Android emulator (Google Nexus 5X - 6.0.0 - API 23).

**Comment by marzolfb** [comment]
@Jarda8 - I'm continuing to look at this issue, but for now I've found you can get the labels to display by setting the margin.left property at 25 or higher

**Comment by marzolfb** [comment]
@SimchaShats I am still unable to reproduce your issue with all the numbers squeezed in the top left corner along the y axis. The previous code and data samples you gave didn't match the screenshot you had previously, so I tried modifying the data to match your screenshot and I still couldn't reproduce it (but I did see another bug which I put in #18). 

I'm guessing I'm missing something you have in the data/code you are working with, could you try including your code & data that produces the result above?

The code/data I am working with that displays labels along the y axis correctly is:

```
import React from 'react';
import { AppRegistry, View } from 'react-native';
import {StockLine} from 'react-native-pathjs-charts';

export class StockLineExample extends React.Component {
  render() {
    var data = [[{"x":3,"y":71},{"x":6,"y":75},{"x":7,"y":61}]];

    var options = {
      width: 275 ,
      height: 200,
      color: '#2980B9',
      margin: {
        top: 20,
        left: 20,
        bottom: 20,
        right: 15
      },
      animate: {
        type: 'delayed',
        duration: 200
      },
      axisX: {
        showAxis: false,
        showLines: true,
        showLabels: true,
        showTicks: true,
        zeroAxis: true,
        orient: 'bottom',
        tickValues: [],
        label: {
          fontFamily: 'Arial',
          fontSize: 8,
          fontWeight: true,
          fill: '#34495E'
        }
      },
      axisY: {
        showAxis: false,
        showLines: true,
        showLabels: true,
        showTicks: true,
        zeroAxis: true,
        orient: 'left',
        tickValues: [],
        label: {
          fontFamily: 'Arial',
          fontSize: 8,
          fontWeight: true,
          fill: '#34495E'
        }
      }
    };

    return (
      <View style={{flex:1,alignItems:"center",justifyContent:"center"}}>
        <StockLine
          data={data}
          options={options}
          xKey='x' yKey='y' />
      </View>
    );
  }
}

AppRegistry.registerComponent('example', () => StockLineExample);
```

**Comment by SimchaShats** [comment]
Hmmm... I think it's not related to data set, because I tried different data and also other graphs like bars and pie have all numbers in the left top corner(pie has names in the left top corner)... May be it's related to parent container of my component, I think I'll need to try your code sample to run in separate file...

**Comment by Jarda8** [comment]
I had exactly the same problem with labels being displayed in the top left corner, but it changed after the update to version 0.0.21.

**Comment by SimchaShats** [comment]
@Jarda8 Thanks, I did it last time but it didn't help... now I removed ALL node_modules, and cleaned project and now this helped(install new dependencies (0.0.21)

**Comment by kasterlod** [comment]
If we set margin left(for left labels visible) then axisX seems like have setted margin left too and it looks not as fine as we would like, it's not centered under each bar

**Comment by marzolfb** [comment]
@kasterlod I don't see the connection between your issue and this #11 issue you expanded on. Could you open a new issue?

**Comment by kasterlod** [comment]
yes, sorry
