### ISSUE TITLE
Changing default gray background to transparent

### ISSUE THREAD

**Issue by tokict** [capitalone/react-native-pathjs-charts#185]
I dont see any way of changing the background of the chart to transparent. Is this possible?

**Comment by shrupa** [comment]
You should be able to render the chart inside a view with style element.
`<View style={styles.container}>
        <SmoothLine data={data} options={options} xKey='x' yKey='y' />
   </View>
`
And style definition-
`const styles = StyleSheet.create({
  container: {
    flex: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
});
`

**Comment by tokict** [comment]
Oh, so it takes it from the  parent and if there is no background on the parent it will default to gray. I was somehow expecting it to inherit from main container. Thanks for the tip mate!
