### ISSUE TITLE
Unhandled Promise rejection due to babel-polyfill

### ISSUE THREAD

**Issue by dgladkov** [capitalone/react-native-pathjs-charts#195]
- [x] I have searched for existing issues
- [x] I have provided detailed instructions that can reproduce the issue (including code and data necessary)

Package versions:
```
{
    "react": "16.0.0-alpha.12",
    "react-native": "0.48.3",
    "react-native-pathjs-charts": "0.0.31",
    "react-native-svg": "5.4.1"
}
```

Traceback:
```
console.error: "Unhandled promise rejection", {}

console.error
    YellowBox.js:67:10
<unknown>
    es6.promise.js:97:18
module.exports
    _perform.js:3:26
<unknown>
    es6.promise.js:91:15
<unknown>
    JSTimers.js:295:17
_callTimer
    JSTimers.js:148:6
_callImmediatesPass
    JSTimers.js:196:6
Object.callImmediates
    JSTimers.js:464:11
MessageQueue.__callImmediates
    MessageQueue.js:282:13
```

Removing `import 'babel-polyfill'` solves the problem.

Issue #62 and related PR #64 that introduced `babel-polyfill`. Can we try to reproduce #62 on the latest RN release to make sure we still need the polyfill?

**Comment by elbuild** [comment]
I'm seeing the same error on:

{
    "react": "16.0.0-alpha.12",
    "react-native": "0.47.1",
    "react-native-pathjs-charts": "0.0.31",
    "react-native-svg": "^6.0.0-rc1"
}

and it looks like removing `import 'babel-polyfill'` fixes the issue. I also think we should check if polyfill is still needed.

**Comment by thiswhy** [comment]
I have the same problem @elbuild ,had you sovle this problem?and  how?thans!

**Comment by marzolfb** [comment]
Closing now that #211 has been merged into master

**Comment by insidelabs** [comment]
With this fix, we're seeing the return of:

undefined is not a function (evaluating '_iterator[typeof Symbol === 'function' ? Symbol.iterator: '@@iterator']()')

Specifically on android

**Comment by marzolfb** [comment]
Curious what imports you have in your app? When I removed babel-polyfill, I also updated the example app and replaced: 

```
import 'babel-polyfill'
```

with

```
import 'core-js/es6/symbol'
import 'core-js/fn/symbol/iterator'
```
