### ISSUE TITLE
Pie graph doesn't render with only 1 data item

### ISSUE THREAD

**Issue by SimchaShats** [capitalone/react-native-pathjs-charts#20]
When there is only data field, it draw only one line instead of circle.
By the wat StockLine and SmoothLine need minimum 3 ponts of data to build it or if there are less then 3 points it crashes.

**Comment by Jarda8** [comment]
Is there any progress with this issue?

**Comment by marzolfb** [comment]
Not quite yet but this one and #4 are things I am prioritizing higher than others to address first as is cleaning up the jest tests on the pie chart.

**Comment by eriksape** [comment]
umm maybe a little hack sending a empty value first and last would work

**Comment by NeETsu** [comment]
Hello
as first great chart tool :)

i am using the tool to display pie chart dynamically (building the chart when the user selects the data to display). I am also showing with a Text in the middle of the Chart. I found that if i have only one item selected (drawing the chart with only 1 Item) then the middle of the Chart is not Transparent but white. 

Is these a known Issue?
