### ISSUE TITLE
http://www.capitalone.io/react-native-pathjs-charts/ throws error 404

### ISSUE THREAD

**Issue by VanessaChu** [capitalone/react-native-pathjs-charts#225]
Cannot access page http://www.capitalone.io/react-native-pathjs-charts/ anymore

**Comment by Amurmurmur** [comment]
@VanessaChu same issue here

**Comment by marzolfb** [comment]
Not sure why the custom domain isn't working anymore but this standard github URL does:

https://capitalone.github.io/react-native-pathjs-charts/

I updated the docs link in the README to point to this URL.
