### ISSUE TITLE
Getting rid of Line Fill For StockLines/SmoothLines

### ISSUE THREAD

**Issue by Csear007** [capitalone/react-native-pathjs-charts#230]
Before filing an issue please ensure the following boxes are checked, if applicable:

- [x ] I have searched for existing issues
- [ x] I have provided detailed instructions that can reproduce the issue (including code and data necessary)

So I want to use either the StockLine or SmoothLine to represent a multiple line chart graph, however I haven't been able to get rid of the default fill area under each of the line. Does anybody know how I would manage that?

**Comment by soloviola** [comment]
Check toggle options.showAreas

**Comment by Csear007** [comment]
Thanks that's exactly what I needed, but on a side note do you know how I can just show the area for a certain line and not all the lines I have in the chart?
