### ISSUE TITLE
Charts not showing properly on Android

### ISSUE THREAD

**Issue by M3po** [capitalone/react-native-pathjs-charts#26]
I have installed this library by the guide also used your example as starting point (used your example data also). But when i opened it the chart wasnt showing properly 

![unnamed](https://cloud.githubusercontent.com/assets/10938600/20383364/bacb4d24-acaf-11e6-9315-24f34dff47ec.png)

I have tried this with every chart, its the same there is always "offset" (see picture). Also i tried to change margins (i have set chart margins to 0 and margins of the View to 20) this sets dots  ok but since the x,y axis are out of view their titles don't show.

Also to add i am using Android 6.0.1 on device.

**Comment by M3po** [comment]
for quick fix i have edit

```
let offset = {
      x: chartArea.margin.left * -1,  
      y: chartArea.margin.top * -1
    }

```
to: 
```
let offset = {
      x: 0,  
      y: 0
    }

```

Axis.js in library to suit my needs.

**Comment by marzolfb** [comment]
When you say "on device" I assume you using a real device rather than an emulator, correct? What type of device (Nexus 5, etc...) are you using to test with?

**Comment by M3po** [comment]
Yes i am using real device its Samsung Galaxy A3.

**Comment by MattyK14** [comment]
I'm getting this issue on both platforms. Not with the downloaded example project, but even with the example copied and pasted into a brand new project. Possible bug introduced with newer React-Native?
