### ISSUE TITLE
Way to extend y axis line within scale?

### ISSUE THREAD

**Issue by M3po** [capitalone/react-native-pathjs-charts#31]
I wanted to extend y axis line (showing no data but to be drawn in smoothline graph) in the scale ratio. I just cant figure out how would i do it. `this.chartType` handles this (if i am correct)

**Comment by marzolfb** [comment]
Not sure I understand what "this.chartType handles this" means but there is no built-in configurable way (that I can see) to easily do what you want. The Line.js code responsible for drawing the SmoothLine chart is determining min and max values from the input data to determine lengths of x and y axis lines. Any tweaks to extending axis lines beyond max values would involve making changes to Axis.js. The recent introduction of a configurable "tailLength" in Axis.js (length that the line extends to the left of the y-axis and below the x-axis) illustrates an example way of controlling the axis line length in a manner not driven solely on the input data values provided. It seems like a similar approach could be made to allow for more flexible axis lengths. I would welcome a PR to make the axis line lengths more controllable via configuration.

**Comment by M3po** [comment]
by this.chartType as i understood gets arguments min-max, of data, height and width of graph from options, then it returns scale. As for example in line.js `<Path d={ c.area.path.print() } .. />` . Thank you for explaination, I will try to do something like this. And to explain to you why i need this is because i would like to color " a region" (by this i mean value from (y1,maxX) to (y2,maxX) i did this like 
```
if(this.props.regions != 'undefined'){
    regions = _.map(this.props.regions, function (c, i) {
         let y1 = chart.yscale(c.from)
         let y2 = chart.yscale(c.to)
         let height = (y2 - y1);
         return <Rect key={'region' + i} x={offset.x} y={y1} width={chartArea.x.max} height={height} fill={c.fill}/>
    }.bind(this))
```
But the problem is if this `region` y is greater than max value of data, it wont be drawn on the graph.

**Comment by marzolfb** [comment]
FYI - I discovered that there is a newer version of paths-js (0.4.5) which supports a configuration option to specify min and max values to scale the chart beyond max/min data points. 

I also like the range band ideas you are trying to attempt above.

I'm working on a PR to expose the min/max options and show the ability to provide regions as you have above (unless you'd rather I let you do that, @M3po?)

**Comment by M3po** [comment]
@marzolfb That is great, as i tried to but in the end didn't find any solution (would take me longer than i wanted)  and left it as is (if data is in the range of region then it shows it). You can put the ability for the regions i don't mind, I'm just glad i could be of help.
