### ISSUE TITLE
How i can scroll chart horizontally?

### ISSUE THREAD

**Issue by gadfil** [capitalone/react-native-pathjs-charts#35]
Hi
For first, thank you for cool library!
How i can scroll chart horizontally?

**Comment by marzolfb** [comment]
You should be able to do this by wrapping a `ScrollView` around your chart component and setting the `horizontal` property to true. For example, take the example app and start by taking one of the charts (like the Pie chart) and set its width to a large enough number to make it not fit on the screen. Then, it should be a matter of changing this:

```
     <View>
        <Pie
          data={data}
          options={options}
          accessorKey="population" />
      </View>
```

to this:

```
    <ScrollView horizontal={true}>
        <Pie
          data={data}
          options={options}
          accessorKey="population" />
      </ScrollView>
```

and now you should be able to scroll horizontally.
