### ISSUE TITLE
Unknown name module:'react-native-pathjs-charts'

### ISSUE THREAD

**Issue by chen236310** [capitalone/react-native-pathjs-charts#38]
I had  added  the library to My React Native project:
npm install react-native-pathjs-charts --save
react-native link react-native-svn.Then do  like example pie ,import { Pie } from 'react-native-paths-charts' and run My project in  android ,it output 'Unknow named module::'react-native-paths-charts''.
   What should I do to  resolute this ?I predicated somebody  can help me.

**Comment by marzolfb** [comment]
You want to use `from react-native-pathjs-charts` instead of `from react-native-paths-charts`

**Comment by chen236310** [comment]
Thank you very much for your answer. When I download example ,run in android, it came out error,'No
ViewManager defined for class RNSVGGroup',How do I  solve this error, thank you in advance.

**Comment by marzolfb** [comment]
Did you run `npm install` as the readme says? What specific things have you tried to resolve the error?

**Comment by marzolfb** [comment]
@chen236310 Is this still an issue for you?

**Comment by marzolfb** [comment]
Closing this out after not hearing a response on the questions above for awhile.
