### ISSUE TITLE
Way to do a basic line chart, no fill color under line, no smoothing of line.

### ISSUE THREAD

**Issue by dgeswein-dlx** [capitalone/react-native-pathjs-charts#39]
Do you have a way to just do a very basic line chart - or use the existing scatter chart, but connect the points with straight lines?

**Comment by marzolfb** [comment]
Yes.  

To get straight lines instead of smooth lines you want to use the `StockLine` chart type instead of the `SmoothLine` chart type. 

To remove the fill (though this isn't documented on the wiki or shown in the example app), you can add this property to your options object:

```
showAreas: false,
```
