### ISSUE TITLE
Line Chart - Line Thickness/Width

### ISSUE THREAD

**Issue by edencakir** [capitalone/react-native-pathjs-charts#44]
Is there a way to set the line thickness/width? If we are to use `showAreas: false` it becomes really difficult to see the lines.

**Comment by marzolfb** [comment]
That configuration option, unfortunately, is not directly exposed in this library (yet). It should be a pretty quick PR for someone else or myself to add the `strokeWidth` property on [line 88 of Line.js](https://github.com/capitalone/react-native-pathjs-charts/blob/master/src/Line.js#L88) (see [the common props documentation on the react-native-svg repo](https://github.com/react-native-community/react-native-svg#common-props)). Feel free to give it a shot if you want.

**Comment by edencakir** [comment]
@marzolfb  I could've change the Options constructor and add default props, but instead I've just followed the `showArea` prop setup. Hope this works, I'm already using this one in my project. Thank you for the help.
