### ISSUE TITLE
How to use flex width on charts?

### ISSUE THREAD

**Issue by lsps9150414** [capitalone/react-native-pathjs-charts#47]
In order to let my app work on both phone and tablet, I need to apply `flex` to everything.
Is there any way to set chart width/height to flex?

**Comment by marzolfb** [comment]
No support for that in this library itself and I would imagine that would be quite a bit of work to support. I'm open to any proposals on approach or pull request contributions that would provide support for this. Feel free to provide feedback and reopen as necessary.

**Comment by petrovakd** [comment]
Not a solution, but can halp you. use Dimensions to calculate width and height and pass it to your graph. for example 
var {width, height} = Dimensions.get('window');
.......
  var options = {
        width: width / 2
        height: height / 5
        color: c.BLUSHBLUE,
......

If you are to use gifferent orientation, handle it to calculate correctly
