### ISSUE TITLE
I want that column and column between each other in my BarChart has scattered points or gaps. 

### ISSUE THREAD

**Issue by Altraman** [capitalone/react-native-pathjs-charts#56]
This is my bar chart:
![qq20170125-113956](https://cloud.githubusercontent.com/assets/23014034/22277204/ab32c6aa-e2f4-11e6-9277-2ad37d9d7b17.png)
But I want to......:
![qq20170125-113937](https://cloud.githubusercontent.com/assets/23014034/22277210/b7f9bfec-e2f4-11e6-8984-210a48be3205.png)

**Comment by marzolfb** [comment]
The `gutter` configuration option is what you want to be adjusting. In the example app, you can see it set to a value of 20 for the basic bar chart:

```
let options = {
      width: 300,
      height: 300,
      margin: {
        top: 20,
        left: 25,
        bottom: 50,
        right: 20
      },
      color: '#2980B9',
      gutter: 20,
```

Also, the structure of the `data` object is maybe not so obvious. If you have a structure like the example app: 
```
let data = [
      [{
        "v": 49,
        "name": "apple"
      }, {
        "v": 42,
        "name": "apple"
      }],
      [{
        "v": 69,
        "name": "banana"
      }, {
        "v": 62,
        "name": "banana"
      }],
      [{
        "v": 29,
        "name": "grape"
      }, {
        "v": 15,
        "name": "grape"
      }]
    ]
```
, you will see something like this:

![image](https://cloud.githubusercontent.com/assets/1242149/22361639/98cfb33e-e410-11e6-8c3c-85d574d899f2.png)

and in that case, `gutter` represents the space between the 2 sets of 3 bars. 

Now, if you have a more simple structure like this:

```
let data = [
      [{
        "v": 49,
        "name": "apple"
      }, {
        "v": 42,
        "name": "banana"
      }]
    ]
```

you will see this:

![image](https://cloud.githubusercontent.com/assets/1242149/22361668/dfafacaa-e410-11e6-90d1-d425ff785a7e.png)

and gutter represents the space between the 2 items in the inner array.

Now if you instead have single-item arrays inside the main data array like this

```
let data = [
      [{
        "v": 49,
        "name": "apple"
      }], [{
        "v": 42,
        "name": "banana"
      }]
    ]
```

, you will see that the `gutter` option is ignored:

![image](https://cloud.githubusercontent.com/assets/1242149/22361724/59a39fb2-e411-11e6-870a-b0faeb37a932.png)

So, to make a long story short, spacing between bars is dictated by both the `gutter` configuration option AND the way you structure your data.

**Comment by Altraman** [comment]
Thank you！ @marzolfb
