### ISSUE TITLE
Example app error - Couldn't find preset "react-native" relative to directory

### ISSUE THREAD

**Issue by marzolfb** [capitalone/react-native-pathjs-charts#63]
I get this error when following the readme instructions to install the example app

```
Error: Couldn't find preset "react-native" relative to directory "<root.dir>/react-native-pathjs-charts"
```

Two ways to workaround this until it gets fixed:
- Remove `.babelrc` from the root directory (`../example`)
- Do `npm install` on the root directory (`../example`)

**Comment by akashnigam010** [comment]
That helped. Thanks!
