### ISSUE TITLE
Always start y-axis from a minimum value (say: 0) irrespective of minimum value of the data?

### ISSUE THREAD

**Issue by irfanayazfm** [capitalone/react-native-pathjs-charts#76]
I want to have my y-axis always start from 0 irrespective of the min value of my data. Is there a way to achieve this?

**Comment by marzolfb** [comment]
I'm not sure I completely I understand what you are trying to achieve and what specific type of chart you are dealing with but I'll give an example a shot as a starting point for discussions. 

Let's start with the "SmoothLineChartBasic" from the example app which normally displays like this:

![image](https://cloud.githubusercontent.com/assets/1242149/22811759/a587a5a6-eef5-11e6-9a28-f30a4c1d9a52.png)

If I understand what you are wanting to do, you don't want that part below y=0 of the y-axis displayed right?

So, in your chart options you can add `min` and max` values (at same level as axisX and axisY) like this:

```
min: 0,
max: 2000,  
axisX: {
        showAxis: true,
        ...   
```

So, that change makes that example chart look like this:

![image](https://cloud.githubusercontent.com/assets/1242149/22811837/1e4282b8-eef6-11e6-97aa-b180addae3ae.png)

Was that basically what you were trying to achieve? Or something different?

**Comment by irfanayazfm** [comment]
Thanks alot. Exactly this!
