### ISSUE TITLE
react-native-svg库不能正常使用

### ISSUE THREAD

**Issue by fangkyi02** [capitalone/react-native-pathjs-charts#81]
debug模式一切正常 编译成release以后 安装完成 打开就直接报 not find DSO libcsslayout.so
release过程中 没有报任何错误 
目前RN版本0.41.2

**Comment by marzolfb** [comment]
After translating this to English, I still do not understand what the problem you have above is. Could you state your problem again (perhaps in English)? I don't think I've seen any error messages referencing libcsslayout.so lately.

I'm thinking you are referencing an error from either ios or android logs you see - could you post the full log snippet where you see the error?

I see you opened [a very similar issue in the react-native-svg repository](https://github.com/react-native-community/react-native-svg/issues/254) - what motivated you to post the same issue to both places?

Given the issue creation on both repositories, I am curious what version of react-native-svg you are targeting that led to the problem you indicated above (what output does `npm list react-native-svg` produce in your application)? This library insists on having version 4.5.0 of react-native-svg and not a newer version (as there are known problems with newer issues - see commentary in some of the recent issues)

**Comment by marzolfb** [comment]
Closing due to lack of feedback for several days.
