### ISSUE TITLE
"undefined is not a function" when I run the example

### ISSUE THREAD

**Issue by kjjacket** [capitalone/react-native-pathjs-charts#86]
When I run the example in rn@0.41.2/paths-js@0.4.5/react-native-svg@4.5.0, I meet a error : 

undefined is not a function (evaluating '_instructions[typeof Symbol==='function'?Symbol.iterator:'@@iterator']()')

points
path.js : 178

render
Radar.js : 99

How to resolve this problem?

**Comment by adriansoghoian** [comment]
@kjjacket How did you resolve this? I'm running into it as well.
