### ISSUE TITLE
Passed an invalid numeric value (NaN, or not-a-number) to CoreGraphics API

### ISSUE THREAD

**Issue by DVassilev** [capitalone/react-native-pathjs-charts#87]
I installed 0.0.24 and am trying to use SmoothLine but nothing is appearing except for this error now:
```
<Error>: Error: this application, or a library it uses, has passed an invalid numeric value (NaN, or not-a-number) to CoreGraphics API and this value is being ignored. Please fix this problem.
```

Any solution? I tried using some sample data but still doesn't work.
```
[[{x:0,y:1}, {x:1, y:1}], [{x: 4, y:5}, {x:6, y:4}]]
```

**Comment by marzolfb** [comment]
Could you show your whole source file where you are using the sample data?

**Comment by DVassilev** [comment]
@marzolfb I added this to the render function to test it:
```
<SmoothLine data={[[{x:0,y:1}, {x:1, y:1}], [{x: 4, y:5}, {x:6, y:4}]]} xKey='Day' yKey='Price' />
```

Which is inside a <View> with the following style:
```
container: {
    position: 'absolute',
    justifyContent: 'center',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0
  }
```

**Comment by marzolfb** [comment]
You want your `xKey` and `ykey` property values to match the key you use in your data (take a look at the SmoothLineBasic chart in the example app as a reference). You are using `x` and `y` as keys in your data but your `xKey` and `yKey` values are 'Day' and 'Price respectively. So, either modify the keys in your data to use 'Day' and 'Price' or modify `xKey` to be 'x' and `yKey` to be 'y'

**Comment by DVassilev** [comment]
@marzolfb Ah I see thank you. I saw the example but assumed the props were just for labelling purposes whereas x and y should be used in the JSON as the wiki was a bit sparse. Thanks!
