### ISSUE TITLE
Axis.js Line 91 will return NaN

### ISSUE THREAD

**Issue by qiangspecial** [capitalone/react-native-pathjs-charts#89]
When i test example `StockLineChartStaticTickLabels`
```javascript
// Axis.js line 91
      lines: ticks.map(c => {
        const lineStart = {x: horizontal ? this.scale(c) + margin.left : xAxis.min + margin.left, y: horizontal ? yAxis.min + margin.top : this.scale(c) + margin.top}
        return Pathjs().moveto(lineStart).lineto(horizontal ? lineStart.x : xAxis.max + margin.left, horizontal ? yAxis.max + (margin.top - tailLength) : lineStart.y)
      },this)
```
`this.scale(c)` will return NaN

**Comment by marzolfb** [comment]
Could you show what your data and options and JSX source looks like?

**Comment by qiangspecial** [comment]
@marzolfb just test the example `StockLineChartStaticTickLabels` in debug, I did not change anything!

**Comment by marzolfb** [comment]
@qiangspecial Thanks for pointing this out. I'm not sure what behavior you saw that motivated you to log the issue, but I did discover that @manjeets12's issue in #4 (`error while updating property 'd' in shadow node of type :RNSVGPath...`) was related and resolved by fixing your issue.
