### ISSUE TITLE
undefined is not a function

### ISSUE THREAD

**Issue by AnselBaikal** [capitalone/react-native-pathjs-charts#90]
![1111111](https://cloud.githubusercontent.com/assets/13342441/23121440/6766ad40-f79b-11e6-8c47-81bb232c063e.png)

undefined is not a function (evaluating 'data.entries()[typeof Symbol==='function'?Symbol.iterator:'@@iterator']()')

**Comment by raymundtusk7** [comment]
I'm getting exactly the same error

**Comment by marzolfb** [comment]
@AnselBaikal and @raymundtusk7 Have either of you looked at #62? Assuming this is the same issue, #85 fixes it and has been merged in here but been published to npm yet. #62 has a workaround that should address it until then.

**Comment by marzolfb** [comment]
@AnselBaikal and @raymundtusk7 I just pushed v0.0.26 of this library (which contains #85) to npm. Assuming the issue logged here is the same in #62, the new version of the library should fix your issue.

**Comment by marzolfb** [comment]
Haven't got a reply in a while. Closing...
