### ISSUE TITLE
Single Item Bar Chart with Spacing 

### ISSUE THREAD

**Issue by mosesmc52** [capitalone/react-native-pathjs-charts#96]
Hi,

I got the bar chart to work. Instead of using multiple categories, I'm using a single item.  The chart doesn't display, spacing between the bars. Is there a configuration parameter that I can use to insert spacing between the bars in the chart? Below is my modified code. 

    let data = [
      [{
        "v": 49,
        "name": "1"
      }],
      [{
        "v": 69,
        "name": "2"
      }],
      [{
        "v": 29,
        "name": "3"
      }],
      [{
        "v": 40,
        "name": "4"
      }]
    ]

    let options = {
      width: 300,
      height: 200,
      margin: {
        top: 20,
        left: 25,
        bottom: 50,
        right: 20
      },
      color: '#3cb3e2',
      gutter: 20,
      animate: {
        type: 'oneByOne',
        duration: 200,
        fillTransition: 3
      },
      axisX: {
        showAxis: false,
        showLines: true,
        showLabels: true,
        showTicks: false,
        zeroAxis: false,
        orient: 'bottom',
        label: {
          fontFamily: 'Arial',
          fontSize: 8,
          fontWeight: false,
          fill: '#34495E'
        }
      },
      axisY: {
        showAxis: false,
        showLines: false,
        showLabels: true,
        showTicks: false,
        zeroAxis: false,
        orient: 'left',
        label: {
          fontFamily: 'Arial',
          fontSize: 8,
          fontWeight: false,
          fill: '#34495E'
        }
      }
    }

<Bar data={data} options={options} accessorKey='v'/>

**Comment by marzolfb** [comment]
Your `data` variable should switch from an array of arrays to an array of objects like this:

```
let data = [
  [{
    "v": 49,
    "name": "1"
  },
  {
    "v": 69,
    "name": "2"
  },
  {
    "v": 29,
    "name": "3"
  },
  {
    "v": 40,
    "name": "4"
  }]
]
```

This should fix it, so I'm closing this but if it doesn't feel free to reopen.

**Comment by mosesmc52** [comment]
It worked.

Thanks
