### ISSUE TITLE
Text in the middle of the Pie Chart

### ISSUE THREAD

**Issue by NeETsu** [capitalone/react-native-pathjs-charts#98]
Before filing an issue please ensure the following boxes are checked, if applicable:

- [x] I have searched for existing issues
- [x] I have provided detailed instructions that can reproduce the issue (including code and data necessary)

Hello
i would like to ask if there is any possibility to set a label in the middle of the Pie chart (in the white area)?

Regards
Nejc

**Comment by marzolfb** [comment]
I think #30 is really similar to what you are asking for here. Could you take a look at that issue and see if the suggestions there address this issue?

**Comment by NeETsu** [comment]
Hello
yes
it is a big help for the Issue
Thank you
